# Generated by Django 2.2.7 on 2019-12-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_To_Substitutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=120, unique=True, verbose_name='food_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='decryption')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='calories')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=120, unique=True, verbose_name='login')),
                ('email', models.CharField(blank=True, max_length=120, unique=True, verbose_name='email')),
                ('created_at', models.DateField(verbose_name='created_at')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='weight')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='age')),
                ('activity', models.PositiveIntegerField(blank=True, max_length=4, null=True, verbose_name='activity')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('city', models.CharField(max_length=120, verbose_name='city')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
                ('street', models.CharField(max_length=120, verbose_name='street')),
                ('street_number', models.PositiveIntegerField(verbose_name='street_number')),
                ('latX', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='latX')),
                ('longY', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='LongY')),
                ('hours', models.TextField(blank=True, null=True, verbose_name='hours')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='rating')),
                ('description', models.TextField(verbose_name='description')),
                ('id_moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('id_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Restaurants')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_decryption', models.TextField(verbose_name='recipe_descyption')),
                ('recipe_foto', models.ImageField(upload_to='', verbose_name='recipe_foto')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Restaruant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='commet')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='rating')),
                ('id_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Restaurants')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='user_comment')),
                ('rating', models.PositiveSmallIntegerField(max_length=5)),
                ('id_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Recipes')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(verbose_name='like')),
                ('id_ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Ingredients')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Ingredients')),
                ('id_recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Substitutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_food_to_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Food_To_Substitutes')),
                ('id_vegan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Ingredients')),
            ],
        ),
    ]
