# Generated by Django 2.2.7 on 2019-12-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_recipes',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
