# Generated by Django 2.2.7 on 2020-02-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='calories',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(blank=True, null=True, verbose_name='Węglowodany'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cellulose',
            field=models.FloatField(blank=True, null=True, verbose_name='Błonnik'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Tłuszcz'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(blank=True, null=True, verbose_name='Kcal'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Białko'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nazwa'),
        ),
    ]
