# Generated by Django 2.2.7 on 2020-03-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='veggies.Ingredient_List', to='veggies.Ingredient'),
        ),
    ]
