# Generated by Django 2.2.7 on 2019-12-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0002_auto_20191215_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='activity'),
        ),
    ]
