# Generated by Django 2.2.7 on 2020-02-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0002_auto_20200218_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='cellulose',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='kcal',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='protein',
        ),
    ]
