# Generated by Django 2.2.7 on 2019-12-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0003_auto_20191215_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_Substitutes',
            new_name='Food_Substitute',
        ),
        migrations.RenameModel(
            old_name='Food_To_Substitutes',
            new_name='Food_To_Substitute',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Preference',
        ),
        migrations.RenameModel(
            old_name='Rating_Recipes',
            new_name='Rating_Recipe',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
