# Generated by Django 2.2.7 on 2020-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0003_auto_20200218_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(blank=True, null=True, verbose_name='Węglowodany'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cellulose',
            field=models.FloatField(blank=True, null=True, verbose_name='Błonnik'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Tłuszcz'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(blank=True, null=True, verbose_name='Kcal'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Białko'),
        ),
    ]
