# Generated by Django 2.2.7 on 2019-12-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0004_auto_20191215_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating_Restaruant',
            new_name='Rating_Restaurant',
        ),
    ]
