# Generated by Django 2.2.7 on 2020-02-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0004_auto_20200218_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_decryption',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_decription',
            field=models.TextField(default=None, verbose_name='recipe_description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.TextField(default='none', max_length=120),
            preserve_default=False,
        ),
    ]
