# Generated by Django 2.2.7 on 2019-12-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0005_auto_20191215_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_to_substitute',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='decription'),
        ),
    ]
