# Generated by Django 2.2.7 on 2020-02-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0006_auto_20200226_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating_restaurant',
            unique_together={('id_user', 'id_restaurant')},
        ),
    ]
