# Generated by Django 2.2.7 on 2020-03-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0007_auto_20200310_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('id_user', 'id_ingredients')},
        ),
    ]
