# Generated by Django 2.2.7 on 2020-03-05 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0008_auto_20200227_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_stamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=None, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating_recipe',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient_list',
            unique_together={('id_ingredient', 'id_recipes')},
        ),
        migrations.CreateModel(
            name='Post_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
                ('data_stamp', models.DateField(default=django.utils.timezone.now)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Post')),
            ],
        ),
    ]
