# Generated by Django 2.2.7 on 2020-03-08 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0008_auto_20200227_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='veggies.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient_list',
            name='id_recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ing', to='veggies.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient_list',
            unique_together={('id_ingredient', 'id_recipes')},
        ),
    ]
