# Generated by Django 2.2.7 on 2020-04-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0010_remove_food_to_substitute_show_on_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeganCuriosities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='curiosity')),
            ],
        ),
    ]
