# Generated by Django 2.2.7 on 2020-03-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0011_auto_20200306_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post_reply',
            old_name='author',
            new_name='user',
        ),
    ]
