# Generated by Django 2.2.7 on 2020-04-11 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0012_auto_20200410_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='main_post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ctig8ylotxru/public/images/main_posts', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_foto',
            field=models.ImageField(null=True, upload_to='ctig8ylotxru/public/images/recipe_fotos', verbose_name='recipe_foto'),
        ),
        migrations.AlterField(
            model_name='reply_post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ctig8ylotxru/public/images/post_replies', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ctig8ylotxru/public/images/restaurants', verbose_name='foto'),
        ),
    ]
