# Generated by Django 2.2.7 on 2020-03-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0013_auto_20200306_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post_reply',
            options={},
        ),
    ]
