# Generated by Django 2.2.7 on 2020-03-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0015_auto_20200306_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post_reply',
            name='id_post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post_reply',
        ),
    ]
