# Generated by Django 2.2.7 on 2020-03-06 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0016_auto_20200306_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
                ('data_stamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
                ('data_stamp', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies.Main_Post')),
            ],
        ),
    ]
