# Generated by Django 2.2.7 on 2020-03-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0019_main_post_reply_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply_post',
            name='id_post',
        ),
        migrations.AddField(
            model_name='reply_post',
            name='id_post_int',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
