# Generated by Django 2.2.7 on 2020-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0020_auto_20200306_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply_post',
            name='title',
            field=models.TextField(default='null'),
        ),
    ]
