# Generated by Django 2.2.7 on 2020-03-06 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0021_reply_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply_post',
            name='data_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
