# Generated by Django 2.2.7 on 2020-03-08 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0025_auto_20200308_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_post',
            name='data_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reply_post',
            name='data_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
