# Generated by Django 2.2.7 on 2020-03-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0026_auto_20200308_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply_post',
            name='title',
        ),
    ]
