# Generated by Django 2.2.7 on 2020-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0027_remove_reply_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_post',
            name='author_id_val',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply_post',
            name='author_id_val',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
