# Generated by Django 2.2.7 on 2020-03-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0028_auto_20200308_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_post',
            name='author_id_val',
        ),
        migrations.RemoveField(
            model_name='reply_post',
            name='author_id_val',
        ),
    ]
