# Generated by Django 2.2.7 on 2020-03-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0029_auto_20200308_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply_post',
            name='title',
            field=models.TextField(default='null'),
        ),
    ]
