# Generated by Django 2.2.7 on 2020-03-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggies', '0031_auto_20200308_2245'),
        ('veggies', '0009_auto_20200308_1606'),
    ]

    operations = [
    ]
