export const tempObj = [
  {
    id: 51,
    ingredients: [
      {
        id: 1641,
        name: "Len, nasiona",
        kcal: 500.0,
        protein: 24.5,
        fat: 31.0,
        carbs: 35.0,
        cellulose: 3.9,
        category: "Orzechy",
      },
      {
        id: 4321,
        name: "Kawa, napar bez cukru",
        kcal: 2.0,
        protein: 0.2,
        fat: 0.0,
        carbs: 0.3,
        cellulose: 0.0,
        category: "Napoje",
      },
      {
        id: 1241,
        name: "Margaryna miękka, 45% tłuszczu",
        kcal: 398.0,
        protein: 0.0,
        fat: 45.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
      {
        id: 811,
        name: "Mąka pszenna, typ 500",
        kcal: 343.0,
        protein: 10.1,
        fat: 1.2,
        carbs: 74.0,
        cellulose: 2.3,
        category: "Produkty zbożowe",
      },
      {
        id: 1661,
        name: "Migdały",
        kcal: 572.0,
        protein: 20.0,
        fat: 52.0,
        carbs: 20.5,
        cellulose: 12.9,
        category: "Orzechy",
      },
      {
        id: 4551,
        name: "Kakao, proszek 16% ",
        kcal: 452.0,
        protein: 19.0,
        fat: 20.9,
        carbs: 51.3,
        cellulose: 0.0,
        category: "Inne",
      },
    ],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Vegan Brownies",
    recipe_decription:
      "Wypróbuj te miękkie brownies bez nabiału i jajek. Są idealne dla\r\nwegan i osób stosujących dietę bezmleczną. Smakują bosko!\r\n\r\nSposób przygotowania:\r\n1. Rozgrzej piekarnik do 170C. Nasmaruj blaszkę i wyłóż w niej\r\npergamin do pieczenia. Połącz siemię lniane z 6 łyżkami wody\r\ni odstaw na 5 minut.\r\n\r\n2. W rondelku rozpuść 120g czekolady, kawy i margaryny z\r\n60ml wody (na małym ogniu). Pozostaw do ostygnięcia.\r\n\r\n3. Dodaj do miski mąkę, migdały, kakao, proszek do pieczenia,\r\n¼ łyżeczki soli i wymieszaj, aby usunąć grudki. Za pomocą\r\nręcznej trzepaczki wymieszaj cukier z roztopioną czekoladą i\r\ndobrze ubijaj, aż będzie gładka i błyszcząca, upewniając się, że\r\ncały cukier dobrze się rozpuści. Wymieszaj mieszankę\r\nsiemienia lnianego, ekstrakt waniliowy i pozostałą czekoladę,\r\na następnie mieszaninę mąki. Przełóż do blaszki.\r\n\r\n4. Piec przez 35-45 minut. Pozostawić do całkowitego\r\nostygnięcia w blaszce, a następnie pokroić w kwadraty.\r\nPrzechowywać w szczelnym pojemniku i jeść w ciągu trzech\r\ndni.",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/Przepis_1.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=T%2Fn8hw8UGZylcyuTh2oDlJifXVU%3D&Expires=1587380632",
    time: 55,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 61,
    ingredients: [
      {
        id: 811,
        name: "Mąka pszenna, typ 500",
        kcal: 343.0,
        protein: 10.1,
        fat: 1.2,
        carbs: 74.0,
        cellulose: 2.3,
        category: "Produkty zbożowe",
      },
      {
        id: 1381,
        name: "Olej rzepakowy uniwersalny",
        kcal: 884.0,
        protein: 0.0,
        fat: 100.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
      {
        id: 2851,
        name: "Sól biała",
        kcal: 0.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Przyprawy",
      },
      {
        id: 601,
        name: "Kasza gryczana",
        kcal: 336.0,
        protein: 12.6,
        fat: 3.1,
        carbs: 69.3,
        cellulose: 5.9,
        category: "Produkty zbożowe",
      },
      {
        id: 1511,
        name: "Borowiki jadalne, suszone",
        kcal: 321.0,
        protein: 37.7,
        fat: 3.1,
        carbs: 39.2,
        cellulose: 7.5,
        category: "Grzyby",
      },
      {
        id: 1401,
        name: "Olej słonecznikowy",
        kcal: 884.0,
        protein: 0.0,
        fat: 100.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
      {
        id: 3691,
        name: "Por",
        kcal: 24.0,
        protein: 2.2,
        fat: 0.3,
        carbs: 5.7,
        cellulose: 2.7,
        category: "Warzywa",
      },
      {
        id: 2831,
        name: "Pieprz czarny",
        kcal: 335.0,
        protein: 11.8,
        fat: 8.6,
        carbs: 62.7,
        cellulose: 20.2,
        category: "Przyprawy",
      },
      {
        id: 1471,
        name: "Oliwa z oliwek",
        kcal: 882.0,
        protein: 0.0,
        fat: 99.6,
        carbs: 0.2,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
    ],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Pierogi z suszonymi grzybami i kaszą gryczaną",
    recipe_decription:
      "Jeden z pomysłów na pierogi z grzybowym farszem i kaszą\r\ngryczaną. Mięciutkie ciasto, aromatyczny farsz i chwila\r\ncierpliwości przy klejeniu, to prosty przepis na sukces na talerzu!\r\n\r\nSposób przygotowania:\r\n\r\n1. Suche składniki na ciasto wymieszaj w misie i powoli dodawaj\r\nciepłą wodę wymieszaną z olejem. Połącz składniki wyrabiając, aż\r\ndo uzyskania gładkiego i miękkiego ciasta.\r\n\r\n2. Kaszę ugotuj, a na patelni z rozgrzanym olejem podsmaż pora oraz\r\nposiekane pieczarki i grzyby suszone. Dopraw solą oraz pieprzem i\r\ndodaj do nich kaszę. Wszystko ugnieć porządnie tłuczkiem do\r\nziemniaków lub zmiksuj blenderem połowę masy i wymieszaj.\r\n\r\n3. Ciasto rozwałkuj na cienką warstwę, wykrawaj równe koła szklanką\r\ni nakładaj 1 łyżeczkę nadzienia do każdego kawałka ciasta.\r\n\r\n4. Pierogi gotuj w osolonym wrzątku i czekaj, aż wypłyną na\r\npowierzchnię. Kolejno je odcedź i podawaj od razu. Smacznego!",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/Przepis_2.JPG?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=EO739fcZTy6GJEbdGL1mnzv6K1w%3D&Expires=1587380632",
    time: 40,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 201,
    ingredients: [
      {
        id: 4011,
        name: "Tofu",
        kcal: 76.0,
        protein: 7.8,
        fat: 4.2,
        carbs: 2.2,
        cellulose: 1.0,
        category: "Warzywa",
      },
      {
        id: 3131,
        name: "Czosnek",
        kcal: 146.0,
        protein: 6.4,
        fat: 0.5,
        carbs: 32.6,
        cellulose: 4.1,
        category: "Warzywa",
      },
      {
        id: 3041,
        name: "Cebula",
        kcal: 30.0,
        protein: 1.4,
        fat: 0.4,
        carbs: 6.9,
        cellulose: 1.7,
        category: "Warzywa",
      },
      {
        id: 4831,
        name: "Papryka wędzona",
        kcal: 40.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Warzywa",
      },
      {
        id: 2841,
        name: "Sos sojowy",
        kcal: 55.0,
        protein: 7.5,
        fat: 0.1,
        carbs: 6.5,
        cellulose: 0.8,
        category: "Przyprawy",
      },
      {
        id: 1381,
        name: "Olej rzepakowy uniwersalny",
        kcal: 884.0,
        protein: 0.0,
        fat: 100.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
      {
        id: 2851,
        name: "Sól biała",
        kcal: 0.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Przyprawy",
      },
    ],
    id_user: {
      id: 81,
      username: "ChePsik_3",
    },
    recipe_name: "Burgery z tofu",
    recipe_decription:
      "Pyszny i prosty sposób na tofu – stek burgery z grilla. Dzięki\r\nmarynacie mają niesamowity smak, który uzupełniają świeże\r\ndodatki. Podaj prosto z grilla na przyjęciu i zawładnij kubkami\r\nsmakowymi swoich gości!\r\n\r\nSposób przygotowania:\r\n1. Koncentrat, posiekany czosnek i cebulę, przyprawy i sosy\r\nwymieszaj, aż powstanie marynata. Umieść w niej kostkę tofu\r\nprzekrojoną na pół wzdłuż – powstaną dwa cienkie\r\nprostokąty. Podlej odrobiną wody, aż marynata będzie\r\nrozprowadzona po całej powierzchni tofu.\r\n2. Po 1 godzinie, a najlepiej noc, marynowania – przystąp do\r\ngrillowania. Rozgrzej porządnie grill i natrzyj go odrobiną\r\noleju. Każdego tofu steka smaż, aż jego powierzchnia pokryje\r\nsię charakterystycznymi lekko przypalonymi liniami.\r\n3. Steki z tofu podaj ze świeżymi warzywami, sosami i domową\r\nbułką. Smacznego!",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/Przepis3.JPG?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=3mMDZS08aWnbX%2B2kZ80Yjyl%2Bf7Q%3D&Expires=1587380632",
    time: 90,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 211,
    ingredients: [
      {
        id: 3271,
        name: "Kalafior",
        kcal: 22.0,
        protein: 2.4,
        fat: 0.2,
        carbs: 5.0,
        cellulose: 2.4,
        category: "Warzywa",
      },
      {
        id: 3681,
        name: "Pomidor",
        kcal: 15.0,
        protein: 0.9,
        fat: 0.2,
        carbs: 3.6,
        cellulose: 1.2,
        category: "Warzywa",
      },
      {
        id: 4821,
        name: "Ciecierzyca gotowana",
        kcal: 97.0,
        protein: 8.0,
        fat: 1.0,
        carbs: 20.0,
        cellulose: 3.0,
        category: "Strączki",
      },
      {
        id: 3131,
        name: "Czosnek",
        kcal: 146.0,
        protein: 6.4,
        fat: 0.5,
        carbs: 32.6,
        cellulose: 4.1,
        category: "Warzywa",
      },
      {
        id: 1471,
        name: "Oliwa z oliwek",
        kcal: 882.0,
        protein: 0.0,
        fat: 99.6,
        carbs: 0.2,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
      {
        id: 2881,
        name: "Syrop klonowy",
        kcal: 274.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 67.9,
        cellulose: 0.8,
        category: "Przyprawy",
      },
      {
        id: 2761,
        name: "Kolendra, nasiona",
        kcal: 298.0,
        protein: 12.4,
        fat: 17.8,
        carbs: 55.0,
        cellulose: 41.9,
        category: "Przyprawy",
      },
      {
        id: 2851,
        name: "Sól biała",
        kcal: 0.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Przyprawy",
      },
      {
        id: 2831,
        name: "Pieprz czarny",
        kcal: 335.0,
        protein: 11.8,
        fat: 8.6,
        carbs: 62.7,
        cellulose: 20.2,
        category: "Przyprawy",
      },
      {
        id: 3621,
        name: "Pietruszka, korzeń",
        kcal: 38.0,
        protein: 2.6,
        fat: 0.5,
        carbs: 10.5,
        cellulose: 4.9,
        category: "Warzywa",
      },
    ],
    id_user: {
      id: 51,
      username: "usera",
    },
    recipe_name: "Pieczony kalafior w pomidorach",
    recipe_decription:
      "Pomidory malinowe, główka kalafiora i trochę ciecierzycy to\r\nskładniki, które wrzucacie na kilka chwil do piekarnika, a\r\nwyciągacie pyszny posiłek! Inspirujcie się sezonowymi\r\nwarzywami będąc na targu i twórzcie kompozycje tak proste jak\r\nta Smacznego!\r\n\r\nSposób przygotowania:\r\n1. Kalafiora umyj i podziel go na mniejsze części, na pojedyncze\r\nkąski. Pomidory pokrój i wraz z czosnkiem, oliwą z oliwek i\r\nsyropem klonowym zmiksuj ręcznym blenderem albo po\r\nprostu mocno ugnieć widelcem.\r\n2. Piekarnik nagrzej do 220°C, a na blachę lub naczynie\r\nżaroodporne. Wyłóż kalafiora i rozsyp na nim równomiernie\r\nciecierzycę. Wszystko zalej rozdrobnionymi pomidorami z\r\nczosnkiem i oliwą. Lekko wymieszaj, obsyp przyprawami i\r\nwłóż do piekarnika.\r\n3. Piecz całość, aż kalafior zacznie przypalać się z wierzchu, a\r\npomidorowy sos odparuje i zgęstnieje. Posyp posiekaną\r\npietruszką i podawaj z ulubioną kaszą, ryżem lub w świeżej\r\nsałatce .",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/Przepis4.JPG?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=78REiPPNLMuFKIrqorpAFth%2F8Y4%3D&Expires=1587380632",
    time: 30,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 221,
    ingredients: [
      {
        id: 781,
        name: "Mąka orkiszowa",
        kcal: 348.0,
        protein: 13.4,
        fat: 1.8,
        carbs: 72.7,
        cellulose: 8.2,
        category: "Produkty zbożowe",
      },
      {
        id: 4761,
        name: "Mleko sojowe",
        kcal: 41.0,
        protein: 6.0,
        fat: 1.4,
        carbs: 4.3,
        cellulose: 0.0,
        category: "Brak",
      },
      {
        id: 4291,
        name: "Wódki",
        kcal: 220.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Alkohol",
      },
      {
        id: 1381,
        name: "Olej rzepakowy uniwersalny",
        kcal: 884.0,
        protein: 0.0,
        fat: 100.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
      {
        id: 4801,
        name: "Cukier Puder",
        kcal: 405.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 100.0,
        cellulose: 0.0,
        category: "Brak",
      },
      {
        id: 4811,
        name: "Wanilia",
        kcal: 288.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 13.0,
        cellulose: 0.0,
        category: "Brak",
      },
    ],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Wegańskie faworki",
    recipe_decription:
      "Pełnoziarniste wegańskie faworki to pozycja obowiązkowa na\r\ntłusty czwartek. Chrupiące, słodkie, ale orkiszowe i\r\npełnoziarniste, dzięki czemu chłoną mniej tłuszczu. Jeśli okażą\r\nsię zbyt zdrowe, po prostu posypcie je toną cukru – od święta!\r\n\r\nSposób przygotowania:\r\n1. Mąką przesyp do dużej miski, najlepiej robota planetarnego.\r\nDodaj do mąki odmierzony olej i chwilę powyrabiaj.\r\nNastępnie dodaj wanilię, cukier puder oraz alkohol.\r\n2. Wyrabiając cały czas ciasto dodawaj do niego małym\r\nciurkiem mleko. Po chwili powinno być gładkie, elastyczne i\r\ndające się rozwałkować (nie może być rzadkie i klejące).\r\n3. Z gotowego ciasta uformuj kulę, owiń ją folią spożywczą i\r\nodstaw na około 30 minut do lodówki. W tym czasie rozgrzej\r\nolej do smażenia.\r\n4. Ciasto rozwałkuj na kilkumilimetrową grubość i ostrym\r\nnożem ponacinaj wzdłuż na wąskie pasy, których środek\r\nrównież ponacinaj jednak nie na całej długości. Jeden koniec\r\nwyciętego ciasta przełóż przez środek wyciętej dziury\r\n5. Faworki smaż na rozgrzanym oleju i gotowe odkładaj na\r\npapier ręcznikowy do odsączenia nadmiar tłuszczu. Na koniec\r\nposyp cukrem i ciesz się swoim szczęściem. Smacznego!",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/Przepis5.JPG?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=%2BSEBntRLLrDB0uvfynGga0DQilk%3D&Expires=1587380632",
    time: 30,
    popularity: 0,
    rating: "3.00",
  },
  {
    id: 231,
    ingredients: [
      {
        id: 3531,
        name: "Ogórek",
        kcal: 13.0,
        protein: 0.7,
        fat: 0.1,
        carbs: 2.9,
        cellulose: 0.5,
        category: "Warzywa",
      },
      {
        id: 2351,
        name: "Melon",
        kcal: 36.0,
        protein: 0.9,
        fat: 0.3,
        carbs: 8.4,
        cellulose: 1.0,
        category: "Owoce",
      },
      {
        id: 1871,
        name: "Awokado",
        kcal: 160.0,
        protein: 2.0,
        fat: 15.3,
        carbs: 7.4,
        cellulose: 3.3,
        category: "Owoce",
      },
      {
        id: 1941,
        name: "Cytryna",
        kcal: 36.0,
        protein: 0.8,
        fat: 0.3,
        carbs: 9.5,
        cellulose: 2.0,
        category: "Owoce",
      },
      {
        id: 4741,
        name: "Śmietana sojowa",
        kcal: 99.0,
        protein: 2.2,
        fat: 9.2,
        carbs: 1.5,
        cellulose: 0.6,
        category: "Brak",
      },
      {
        id: 2761,
        name: "Kolendra, nasiona",
        kcal: 298.0,
        protein: 12.4,
        fat: 17.8,
        carbs: 55.0,
        cellulose: 41.9,
        category: "Przyprawy",
      },
      {
        id: 2851,
        name: "Sól biała",
        kcal: 0.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Przyprawy",
      },
      {
        id: 2831,
        name: "Pieprz czarny",
        kcal: 335.0,
        protein: 11.8,
        fat: 8.6,
        carbs: 62.7,
        cellulose: 20.2,
        category: "Przyprawy",
      },
    ],
    id_user: {
      id: 21,
      username: "mateuszklimek11",
    },
    recipe_name: "Ogórkowy chłodnik z melonem",
    recipe_decription:
      "Chłodnik jest bardzo szybki w wykonaniu, wystarczy do tego\r\nblender kielichowy bądź ręczny.\r\n\r\nSposób przygotowania:\r\n1. Wszystkie składniki dokładnie umyj, szczególnie ogórki,\r\nktórych nie obieraj.\r\n2. Z miąższu melona i ogórków pokrojonych na ćwiartki wydrąż\r\npestki.\r\n3. Awokado pokrój na pół, wyciągnij pestkę i łyżeczką wydrąż\r\ncały miąższ.\r\n4. Do osobnego pojemniczka bądź szklanki wyciśnij sok z\r\ncytryny, przecedź przez sitko.\r\n5. Do osobnego pojemniczka bądź szklanki wyciśnij sok z\r\ncytryny, przecedź przez sitko.\r\n6. 5. Melona, ogórka i awokado wraz z dodatkiem wody\r\n(śmietanki sojowej) zmiksuj w blenderze. Następnie dodaj\r\nzmieloną kolendrę, świeże zioła oraz sól i odrobinę pieprzu.\r\n7. Stopniowo dodawaj sok z cytryny kontrolując kwaskowatość\r\nzupy. Dopraw do smaku.\r\n8. Chłodnik podawaj po porządnym schłodzeniu w lodówce, z\r\npokrojonym w kostkę melonem i/lub pomidorem oraz\r\nświeżymi ziołami.",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/Przepis6.JPG?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=v4ha3OBLVrYCi5XI92ggfLmg38s%3D&Expires=1587380632",
    time: 20,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 241,
    ingredients: [
      {
        id: 3901,
        name: "Soczewica czerwona, nasiona suche",
        kcal: 327.0,
        protein: 25.4,
        fat: 3.0,
        carbs: 57.5,
        cellulose: 8.9,
        category: "Strączki",
      },
      {
        id: 3681,
        name: "Pomidor",
        kcal: 15.0,
        protein: 0.9,
        fat: 0.2,
        carbs: 3.6,
        cellulose: 1.2,
        category: "Warzywa",
      },
      {
        id: 3041,
        name: "Cebula",
        kcal: 30.0,
        protein: 1.4,
        fat: 0.4,
        carbs: 6.9,
        cellulose: 1.7,
        category: "Warzywa",
      },
      {
        id: 3131,
        name: "Czosnek",
        kcal: 146.0,
        protein: 6.4,
        fat: 0.5,
        carbs: 32.6,
        cellulose: 4.1,
        category: "Warzywa",
      },
      {
        id: 3491,
        name: "Marchew",
        kcal: 27.0,
        protein: 1.0,
        fat: 0.2,
        carbs: 8.7,
        cellulose: 3.6,
        category: "Warzywa",
      },
      {
        id: 1381,
        name: "Olej rzepakowy uniwersalny",
        kcal: 884.0,
        protein: 0.0,
        fat: 100.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
      {
        id: 1941,
        name: "Cytryna",
        kcal: 36.0,
        protein: 0.8,
        fat: 0.3,
        carbs: 9.5,
        cellulose: 2.0,
        category: "Owoce",
      },
      {
        id: 2751,
        name: "Kminek, nasiona",
        kcal: 328.0,
        protein: 12.6,
        fat: 13.7,
        carbs: 57.5,
        cellulose: 38.0,
        category: "Przyprawy",
      },
      {
        id: 2821,
        name: "Papryka, suszona (przyprawa)",
        kcal: 324.0,
        protein: 14.8,
        fat: 13.0,
        carbs: 55.7,
        cellulose: 37.4,
        category: "Przyprawy",
      },
      {
        id: 4731,
        name: "Cząber",
        kcal: 1.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Przyprawy",
      },
      {
        id: 2891,
        name: "Tymianek suszony",
        kcal: 285.0,
        protein: 9.1,
        fat: 7.4,
        carbs: 64.0,
        cellulose: 37.0,
        category: "Przyprawy",
      },
    ],
    id_user: {
      id: 61,
      username: "Sebe",
    },
    recipe_name: "Pomidorowy krem z czerwonej soczewicy",
    recipe_decription:
      "Zupa z soczewicy to chyba najbardziej popularna i wręcz\r\npodstawowa zupa kuchni wegańskiej. Doprawiana klasycznie\r\nmajerankiem lub tymiankiem, a nawet curry w mniej\r\nszablonowych przepisach.\r\n\r\nSposób przygotowania:\r\n1. W garnku o grubym dnie lub głębokim rondlu nagrzej olej i\r\npodsmaż drobno posiekaną cebulę, a chwilę potem dodaj\r\nczosnek.\r\n2. Kolejno dodaj pokrojoną w kostkę marchew oraz przepłukaną\r\nsoczewicę i zalej wywarem warzywnym, tak aby w pełni\r\nzakrywał wszystkie składniki na wysokość powyżej 2–3 cm.\r\nGotuj, aż marchew i soczewica będą miękkie.\r\n3. Gdy warzywa zmiękną, dodaj pokrojone pomidory z puszki\r\noraz przyprawy. Gotuj jeszcze przez 10–15 minut, a następnie\r\nzblenduj przy pomocy blendera ręcznego, dodaj sok z cytryny\r\ni dopraw do smaku. Podawaj z gryczkami i świeżymi ziołami.",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/Przepis7.JPG?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=fqSg8AegjWkifOAe70oX2BY6mWI%3D&Expires=1587380632",
    time: 30,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 251,
    ingredients: [
      {
        id: 2931,
        name: "Bataty",
        kcal: 108.0,
        protein: 1.6,
        fat: 0.6,
        carbs: 24.1,
        cellulose: 3.1,
        category: "Warzywa",
      },
      {
        id: 4711,
        name: "Nerkowiec",
        kcal: 553.0,
        protein: 18.2,
        fat: 43.8,
        carbs: 32.7,
        cellulose: 3.3,
        category: "Brak",
      },
      {
        id: 1941,
        name: "Cytryna",
        kcal: 36.0,
        protein: 0.8,
        fat: 0.3,
        carbs: 9.5,
        cellulose: 2.0,
        category: "Owoce",
      },
      {
        id: 3041,
        name: "Cebula",
        kcal: 30.0,
        protein: 1.4,
        fat: 0.4,
        carbs: 6.9,
        cellulose: 1.7,
        category: "Warzywa",
      },
      {
        id: 3131,
        name: "Czosnek",
        kcal: 146.0,
        protein: 6.4,
        fat: 0.5,
        carbs: 32.6,
        cellulose: 4.1,
        category: "Warzywa",
      },
      {
        id: 3261,
        name: "Jarmuż",
        kcal: 29.0,
        protein: 3.3,
        fat: 0.7,
        carbs: 6.1,
        cellulose: 3.8,
        category: "Warzywa",
      },
      {
        id: 4721,
        name: "Płatki drożdżowe",
        kcal: 342.0,
        protein: 28.0,
        fat: 6.0,
        carbs: 32.0,
        cellulose: 0.0,
        category: "Brak",
      },
      {
        id: 1381,
        name: "Olej rzepakowy uniwersalny",
        kcal: 884.0,
        protein: 0.0,
        fat: 100.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Tłuszcze",
      },
      {
        id: 2851,
        name: "Sól biała",
        kcal: 0.0,
        protein: 0.0,
        fat: 0.0,
        carbs: 0.0,
        cellulose: 0.0,
        category: "Przyprawy",
      },
      {
        id: 2831,
        name: "Pieprz czarny",
        kcal: 335.0,
        protein: 11.8,
        fat: 8.6,
        carbs: 62.7,
        cellulose: 20.2,
        category: "Przyprawy",
      },
    ],
    id_user: {
      id: 81,
      username: "ChePsik_3",
    },
    recipe_name: "Makaron z batata",
    recipe_decription:
      "Totalny odjazd! Makaron ze słodkich ziemniaków –\r\nniesamowicie prosty, wyjątkowo słodki, naturalnie\r\nbezglutenowy. Kulinarne horyzonty na nowo poszerzone\r\n\r\nSposób przygotowania:\r\n1. Za pomocą spirali lub obieraczki julienne przygotuj makaron\r\nz batata, wcześniej go obierz i pokrój na mniejsze części.\r\n2. Namoczone nerkowce przełóż do małego, wąskiego naczynia i\r\nzblenduj ręcznym blenderam z sokiem z cytryny, odrobiną\r\nsoli i niewielką ilością wody – aż do uzyskania odpowiedniej,\r\nkremowej konsystencji.\r\n3. Na patelni rozgrzej olej, podsmaż posiekaną cebulę i\r\nprzeciśnięty przez praskę czosnek. Następnie dodaj jarmuż i\r\npoczekaj, aż zmniejszy swoją objętość i zmieni kolor na\r\njaśniejszy. Kolejno dodaj na patelnię makaron z batata i\r\npodmaż go, aż odrobinę zmięknie i nabierze koloru. Długość\r\nduszenia makaronu zależy rownież od jego grubości, więc\r\njeśli Twój makaron powstał z małej obieraczki julienne,\r\ndorzuć go na samym końcu i smaż zaledwie minutę.\r\n4. Następnie dodawaj po kilka łyżek sosu i ew. wody wraz z\r\nupływem czasu. Całość duś przez krótką chwilę, a na koniec\r\ndopraw szczyptą świeżo mielonego pieprzu.",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/Przepis8.JPG?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=a0tAu4Gn%2FQPCbMVlp3X3GBnLhRA%3D&Expires=1587380632",
    time: 25,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 261,
    ingredients: [],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "nazwa",
    recipe_decription: "ewqewqewq ewq weq",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_6.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=w3JQyA6k%2FQYvwMTJjYP2GZYGo5w%3D&Expires=1587380632",
    time: 10,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 271,
    ingredients: [
      {
        id: 31,
        name: "Bagietki francuskie",
        kcal: 283.0,
        protein: 8.7,
        fat: 1.7,
        carbs: 59.2,
        cellulose: 2.0,
        category: "Produkty zbożowe",
      },
    ],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "nazwa",
    recipe_decription: "ewqewqewq ewq weq",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_6.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=w3JQyA6k%2FQYvwMTJjYP2GZYGo5w%3D&Expires=1587380632",
    time: 10,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 281,
    ingredients: [],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Ffafafa",
    recipe_decription: "Ffafafa",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_4.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=cWq8LRnfmJzPPxtOYZeqXIZ0abg%3D&Expires=1587380632",
    time: 30,
    popularity: 0,
    rating: "4.00",
  },
  {
    id: 291,
    ingredients: [],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Ffafafa",
    recipe_decription: "Ffafafa",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_1.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=RM59giZJ5XfgGxwmtch%2BHx1kvfg%3D&Expires=1587380632",
    time: 30,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 301,
    ingredients: [],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Ffafafa",
    recipe_decription: "Ffafafa",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_1.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=RM59giZJ5XfgGxwmtch%2BHx1kvfg%3D&Expires=1587380632",
    time: 30,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 311,
    ingredients: [],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Witajwitaj",
    recipe_decription: '"Test przygotowanie\\r\\n\\r\\ntest przygotowanie"',
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_1.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=RM59giZJ5XfgGxwmtch%2BHx1kvfg%3D&Expires=1587380632",
    time: 10,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 321,
    ingredients: [],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Danie1",
    recipe_decription: '"Przygotowanie1\\r\\n\\r\\nPrzygtoowanie2"',
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_3.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=OwuHLVLfkbs146%2Be2MuwRwmdVbY%3D&Expires=1587380632",
    time: 10,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 331,
    ingredients: [],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Witajwitaj",
    recipe_decription: '"Test1\\r\\n\\r\\nTest2"',
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_3.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=OwuHLVLfkbs146%2Be2MuwRwmdVbY%3D&Expires=1587380632",
    time: 10,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 341,
    ingredients: [],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Chleb",
    recipe_decription: '"Chleb chleb\\r\\n\\r\\nchleb"',
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_2.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=zptGSDFRmHKh3lATFY1AZxd2UX4%3D&Expires=1587380632",
    time: 10,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 351,
    ingredients: [
      {
        id: 231,
        name: "Chleb mazowiecki",
        kcal: 254.0,
        protein: 7.6,
        fat: 1.4,
        carbs: 55.0,
        cellulose: 3.2,
        category: "Produkty zbożowe",
      },
      {
        id: 191,
        name: "Chleb chrupki",
        kcal: 353.0,
        protein: 8.7,
        fat: 2.4,
        carbs: 78.9,
        cellulose: 6.0,
        category: "Produkty zbożowe",
      },
      {
        id: 221,
        name: "Chleb graham",
        kcal: 221.0,
        protein: 8.3,
        fat: 1.7,
        carbs: 48.7,
        cellulose: 6.4,
        category: "Produkty zbożowe",
      },
    ],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Weww",
    recipe_decription: '"jwqej;wqe\\r\\n\\r\\neqwewqewq"',
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_3.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=OwuHLVLfkbs146%2Be2MuwRwmdVbY%3D&Expires=1587380632",
    time: 20,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 361,
    ingredients: [
      {
        id: 191,
        name: "Chleb chrupki",
        kcal: 353.0,
        protein: 8.7,
        fat: 2.4,
        carbs: 78.9,
        cellulose: 6.0,
        category: "Produkty zbożowe",
      },
      {
        id: 241,
        name: "Chleb mieszany jasny, rodzynkowy",
        kcal: 261.0,
        protein: 5.8,
        fat: 1.4,
        carbs: 58.6,
        cellulose: 3.1,
        category: "Produkty zbożowe",
      },
      {
        id: 211,
        name: "Chleb ekstrudowany żytni",
        kcal: 383.0,
        protein: 8.2,
        fat: 6.1,
        carbs: 78.6,
        cellulose: 5.8,
        category: "Produkty zbożowe",
      },
    ],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "aaaaaa",
    recipe_decription: "eqwe qwkeqq\r\n\r\nSSSSSSSSSS\ntrzeca linia",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_3.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=OwuHLVLfkbs146%2Be2MuwRwmdVbY%3D&Expires=1587380632",
    time: 10,
    popularity: 0,
    rating: "5.00",
  },
  {
    id: 371,
    ingredients: [
      {
        id: 191,
        name: "Chleb chrupki",
        kcal: 353.0,
        protein: 8.7,
        fat: 2.4,
        carbs: 78.9,
        cellulose: 6.0,
        category: "Produkty zbożowe",
      },
    ],
    id_user: {
      id: 1,
      username: "mateuszklimek",
    },
    recipe_name: "Przepis1",
    recipe_decription: "Chleb \r\n\r\nPrzygotuj",
    recipe_foto:
      "https://cloud-cube-eu.s3.amazonaws.com/mgtu0qz8fwtg/public/images/recipe_fotos/veganimg_3.jpg?AWSAccessKeyId=AKIA37SVVXBH5RWT7FHI&Signature=OwuHLVLfkbs146%2Be2MuwRwmdVbY%3D&Expires=1587380632",
    time: 10,
    popularity: 0,
    rating: "5.00",
  },
];
